import type {
  Challenge,
  Faculty,
  IndustryPartner,
  Notification,
  Project,
  Student,
  University,
  User,
} from "./types";

export const DEMO_ACCOUNTS: { user: User; password: string }[] = [
  {
    password: "Demo@123",
    user: { id: "u-cit", name: "Sunita Oraon", email: "citizen@demo.in", role: "CITIZEN", district: "Gumla", title: "Community Member, Raidih Block" },
  },
  {
    password: "Demo@123",
    user: { id: "u-adm", name: "Rajesh Kumar Sinha", email: "admin@demo.in", role: "ADMIN", district: "Ranchi", title: "Joint Secretary, Dept. of Higher & Technical Education", organization: "Government of Jharkhand" },
  },
  {
    password: "Demo@123",
    user: { id: "u-uni", name: "Dr. Anjali Verma", email: "university@demo.in", role: "UNIVERSITY", district: "Ranchi", title: "Dean, Research & Innovation", organization: "IIIT Ranchi", organizationId: "uni-iiitr" },
  },
  {
    password: "Demo@123",
    user: { id: "u-ind", name: "Vikram Mahato", email: "industry@demo.in", role: "INDUSTRY", district: "Jamshedpur", title: "Head of CSR Partnerships", organization: "Tata Steel Foundation", organizationId: "ind-tsf" },
  },
];

export const UNIVERSITIES: University[] = [
  {
    id: "uni-iiitr",
    name: "Indian Institute of Information Technology, Ranchi",
    shortName: "IIIT Ranchi",
    district: "Ranchi",
    departments: ["Computer Science & Engineering", "Electronics & Communication", "Environmental Science", "Management Studies"],
    researchAreas: ["Water quality sensing", "Embedded systems", "Rural IoT deployments", "Data analytics for governance"],
    laboratories: ["IoT & Embedded Systems Lab", "Environmental Monitoring Lab", "Data Science Lab"],
    expertise: ["IoT", "Environmental Science", "Computer Vision", "Data Science", "Mobile Apps"],
    previousProjects: 9,
    activeProjects: 3,
  },
  {
    id: "uni-bit",
    name: "Birla Institute of Technology, Mesra",
    shortName: "BIT Mesra",
    district: "Ranchi",
    departments: ["Civil Engineering", "Chemical Engineering", "Electrical Engineering", "Biotechnology"],
    researchAreas: ["Water treatment", "Renewable energy systems", "Structural engineering", "Agri-biotech"],
    laboratories: ["Water & Wastewater Lab", "Renewable Energy Lab", "Remote Sensing Lab"],
    expertise: ["Civil Engineering", "Chemistry", "Renewable Energy", "Electrical Engineering", "GIS"],
    previousProjects: 14,
    activeProjects: 5,
  },
  {
    id: "uni-ru",
    name: "Ranchi University",
    shortName: "Ranchi University",
    district: "Ranchi",
    departments: ["Geology", "Public Health", "Social Work", "Economics"],
    researchAreas: ["Community health", "Tribal development", "Groundwater geology"],
    laboratories: ["Public Health Lab", "GIS Centre"],
    expertise: ["Public Health", "Behavioural Science", "Hydrology", "GIS"],
    previousProjects: 6,
    activeProjects: 2,
  },
  {
    id: "uni-nit",
    name: "National Institute of Technology, Jamshedpur",
    shortName: "NIT Jamshedpur",
    district: "East Singhbhum",
    departments: ["Mechanical Engineering", "Electrical Engineering", "Computer Science", "Production Engineering"],
    researchAreas: ["Power systems", "Smart mobility", "Manufacturing"],
    laboratories: ["Power Systems Lab", "Robotics Lab", "Product Design Studio"],
    expertise: ["Electrical Engineering", "Power Systems", "Product Design", "Operations Research", "Assistive Tech"],
    previousProjects: 11,
    activeProjects: 4,
  },
];

export const FACULTY: Faculty[] = [
  { id: "fac-1", name: "Dr. Priya Kumari", department: "Electronics & Communication", expertise: ["IoT", "Sensor networks"], universityId: "uni-iiitr" },
  { id: "fac-2", name: "Dr. Manoj Tirkey", department: "Environmental Science", expertise: ["Water chemistry", "Field testing"], universityId: "uni-iiitr" },
  { id: "fac-3", name: "Dr. Sameer Ahmad", department: "Computer Science & Engineering", expertise: ["Data platforms", "Mobile apps"], universityId: "uni-iiitr" },
  { id: "fac-4", name: "Prof. Rina Das", department: "Management Studies", expertise: ["Rural business models", "Impact evaluation"], universityId: "uni-iiitr" },
];

export const STUDENTS: Student[] = [
  { id: "stu-1", name: "Aarav Munda", department: "CSE", year: "3rd year", universityId: "uni-iiitr" },
  { id: "stu-2", name: "Neha Singh", department: "CSE", year: "4th year", universityId: "uni-iiitr" },
  { id: "stu-3", name: "Rohit Kumar", department: "ECE", year: "3rd year", universityId: "uni-iiitr" },
  { id: "stu-4", name: "Pooja Kachhap", department: "ECE", year: "4th year", universityId: "uni-iiitr" },
  { id: "stu-5", name: "Sandeep Lakra", department: "Environmental Science", year: "M.Sc. 1st year", universityId: "uni-iiitr" },
  { id: "stu-6", name: "Meera Hansda", department: "Environmental Science", year: "M.Sc. 2nd year", universityId: "uni-iiitr" },
  { id: "stu-7", name: "Kunal Prasad", department: "Management", year: "MBA 1st year", universityId: "uni-iiitr" },
  { id: "stu-8", name: "Asha Toppo", department: "Management", year: "MBA 2nd year", universityId: "uni-iiitr" },
];

export const INDUSTRY: IndustryPartner[] = [
  { id: "ind-tsf", name: "Tata Steel Foundation", sector: "CSR Foundation", district: "East Singhbhum", supportTypes: ["Funding", "Deployment", "Pilot partner"], capabilities: ["Community programmes", "Water", "Health", "Deployment"], csrBudgetLakh: 450 },
  { id: "ind-jwt", name: "Jharkhand Water Tech Pvt Ltd", sector: "Water technology MSME", district: "Ranchi", supportTypes: ["Hardware", "Technology", "Testing"], capabilities: ["IoT hardware", "Water sensors", "Filtration"], csrBudgetLakh: 25 },
  { id: "ind-agri", name: "AgriSense Labs", sector: "Agritech startup", district: "Hazaribagh", supportTypes: ["Technology", "Mentorship"], capabilities: ["Computer vision", "Mobile apps", "Agronomy"], csrBudgetLakh: 12 },
  { id: "ind-ccl", name: "Central Coalfields CSR Cell", sector: "PSU CSR", district: "Ranchi", supportTypes: ["Funding", "Deployment"], capabilities: ["Rural infrastructure", "Energy", "Education"], csrBudgetLakh: 600 },
];

const daysAgo = (d: number) => new Date(Date.now() - d * 864e5).toISOString();

const mk = (c: Partial<Challenge> & Pick<Challenge, "id" | "title" | "category" | "location">): Challenge => ({
  code: c.id.toUpperCase().replace("ch-", "JH-CH-"),
  submittedBy: "u-other",
  submitterName: "Community reporter",
  description: "",
  subcategory: "",
  affectedPopulation: 500,
  issueDuration: "1-5 years",
  frequency: "Daily",
  urgency: "High",
  severity: "High",
  priority: "HIGH",
  priorityScore: 70,
  innovationScore: 70,
  status: "SUBMITTED",
  evidence: [],
  similarChallenges: [],
  reportCount: 1,
  recommendedUniversities: [],
  timeline: [{ status: "SUBMITTED", at: c.createdAt ?? daysAgo(10), by: "Citizen" }],
  createdAt: daysAgo(10),
  ...c,
});

export const CHALLENGES: Challenge[] = [
  mk({
    id: "ch-1001",
    title: "Drinking water contamination in Raidih block villages",
    description:
      "Handpumps in Raidih, Kondra and nearby villages produce yellowish water with a metallic taste. Several children have had recurring stomach illnesses since the last monsoon. The panchayat has no way to test water quality regularly.",
    category: "Water & Sanitation",
    subcategory: "Drinking Water",
    location: { district: "Gumla", block: "Raidih", village: "Kondra", lat: 22.98, lng: 84.36 },
    affectedPopulation: 850,
    urgency: "Critical",
    severity: "Critical",
    priority: "CRITICAL",
    priorityScore: 91,
    innovationScore: 87,
    status: "IN_PROGRESS",
    reportCount: 23,
    isMaster: true,
    clusterId: "cl-1",
    submittedBy: "u-cit",
    submitterName: "Sunita Oraon",
    evidence: [
      { id: "ev-1", type: "photo", name: "handpump-kondra.jpg", caption: "Discoloured water from Kondra handpump" },
      { id: "ev-2", type: "photo", name: "storage-tank.jpg", caption: "Sediment in household storage" },
      { id: "ev-3", type: "document", name: "phc-visit-register.pdf", caption: "PHC illness register, Jul–Aug" },
    ],
    ai: {
      category: "Water & Sanitation",
      subcategory: "Drinking Water",
      severity: "Critical",
      priority: "CRITICAL",
      priorityScore: 91,
      innovationScore: 87,
      confidence: 0.94,
      similarCount: 23,
      reason: "Critical drinking-water contamination affects 850 residents and presents an immediate public-health risk.",
      summary: "Critical drinking-water contamination affects 850 residents and presents an immediate public-health risk.",
      aiClassified: true,
      requiresManualReview: false,
    },
    recommendedUniversities: [
      { universityId: "uni-iiitr", score: 94, reasons: ["IoT expertise", "Environmental research", "Relevant faculty", "Suitable laboratory facilities"] },
      { universityId: "uni-bit", score: 89, reasons: ["Water treatment research", "Water & Wastewater Lab", "Civil engineering faculty"] },
      { universityId: "uni-ru", score: 81, reasons: ["Groundwater geology", "Public health outreach"] },
    ],
    assignedUniversity: "uni-iiitr",
    projectId: "prj-1",
    createdAt: daysAgo(62),
    timeline: [
      { status: "SUBMITTED", at: daysAgo(62), by: "Sunita Oraon" },
      { status: "UNDER_REVIEW", at: daysAgo(60), by: "Platform" },
      { status: "VALIDATED", at: daysAgo(57), by: "R. K. Sinha", note: "Merged 23 reports into master challenge" },
      { status: "MATCHED", at: daysAgo(56), by: "R. K. Sinha", note: "Assigned to IIIT Ranchi" },
      { status: "PROJECT_CREATED", at: daysAgo(49), by: "IIIT Ranchi" },
      { status: "IN_PROGRESS", at: daysAgo(40), by: "IIIT Ranchi", note: "Prototype phase started" },
    ],
  }),
  mk({
    id: "ch-1002",
    title: "Paddy blast disease spreading across Barhi farms",
    description: "Farmers in Barhi report brown lesions on paddy leaves spreading field to field. No local expert to identify the disease early; losses estimated at 30% last season.",
    category: "Agriculture",
    subcategory: "Crop Disease",
    location: { district: "Hazaribagh", block: "Barhi", village: "Chouparan Road", lat: 24.3, lng: 85.42 },
    affectedPopulation: 1200,
    urgency: "High",
    priorityScore: 84,
    innovationScore: 82,
    status: "VALIDATED",
    reportCount: 7,
    recommendedUniversities: [
      { universityId: "uni-iiitr", score: 88, reasons: ["Computer vision expertise", "Mobile app development"] },
      { universityId: "uni-bit", score: 79, reasons: ["Agri-biotech research"] },
    ],
    createdAt: daysAgo(21),
    timeline: [
      { status: "SUBMITTED", at: daysAgo(21), by: "Citizen" },
      { status: "VALIDATED", at: daysAgo(18), by: "R. K. Sinha" },
    ],
  }),
  mk({
    id: "ch-1003",
    title: "No doctor at PHC for 40 km radius in Chhatarpur",
    description: "The primary health centre has had no resident doctor for eight months. Pregnant women travel 40 km to Medininagar for check-ups; emergencies are handled by an untrained pharmacist.",
    category: "Healthcare",
    subcategory: "Primary Care Access",
    location: { district: "Palamu", block: "Chhatarpur", village: "Chhatarpur", lat: 24.18, lng: 84.17 },
    affectedPopulation: 6000,
    urgency: "Critical",
    severity: "Critical",
    priorityScore: 89,
    innovationScore: 74,
    status: "UNDER_REVIEW",
    reportCount: 4,
    createdAt: daysAgo(6),
  }),
  mk({
    id: "ch-1004",
    title: "Girls' school attendance drops sharply after class 6",
    description: "Attendance of girls in the upper primary school falls below 50% after class 6. Reasons cited: distance, lack of toilets and sibling care responsibilities.",
    category: "Education",
    subcategory: "School Attendance",
    location: { district: "Dumka", block: "Jama", village: "Kathikund Road", lat: 24.35, lng: 87.22 },
    affectedPopulation: 340,
    urgency: "Medium",
    severity: "Medium",
    priorityScore: 71,
    innovationScore: 78,
    status: "SUBMITTED",
    reportCount: 2,
    createdAt: daysAgo(3),
  }),
  mk({
    id: "ch-1005",
    title: "Uncollected household waste in Jharia colonies",
    description: "Waste has not been collected for weeks in colonies near Jharia; open burning of plastic is common. Residents report respiratory issues.",
    category: "Environment",
    subcategory: "Solid Waste",
    location: { district: "Dhanbad", block: "Jharia", village: "Bhowra", lat: 23.74, lng: 86.41 },
    affectedPopulation: 4500,
    urgency: "High",
    priorityScore: 79,
    innovationScore: 69,
    status: "VALIDATED",
    reportCount: 11,
    recommendedUniversities: [{ universityId: "uni-bit", score: 86, reasons: ["Environmental engineering", "Logistics research"] }],
    createdAt: daysAgo(30),
    timeline: [
      { status: "SUBMITTED", at: daysAgo(30), by: "Citizen" },
      { status: "VALIDATED", at: daysAgo(25), by: "R. K. Sinha" },
    ],
  }),
  mk({
    id: "ch-1006",
    title: "Unreliable electricity for tribal hamlets in Kolebira",
    description: "Hamlets receive electricity 3–4 hours a day. Students cannot study after dark and the health sub-centre cannot store vaccines.",
    category: "Electricity",
    subcategory: "Power Outage",
    location: { district: "Simdega", block: "Kolebira", village: "Kolebira", lat: 22.68, lng: 84.5 },
    affectedPopulation: 900,
    urgency: "High",
    priorityScore: 77,
    innovationScore: 85,
    status: "MATCHED",
    assignedUniversity: "uni-nit",
    reportCount: 5,
    recommendedUniversities: [{ universityId: "uni-nit", score: 92, reasons: ["Power systems research", "Renewable energy lab"] }],
    createdAt: daysAgo(40),
    timeline: [
      { status: "SUBMITTED", at: daysAgo(40), by: "Citizen" },
      { status: "VALIDATED", at: daysAgo(35), by: "R. K. Sinha" },
      { status: "MATCHED", at: daysAgo(33), by: "R. K. Sinha", note: "Assigned to NIT Jamshedpur" },
    ],
  }),
  mk({
    id: "ch-1007",
    title: "No wheelchair access at block office and bus stand",
    description: "The block development office, bank and bus stand have steps without ramps. Elderly and disabled residents depend on others to access services.",
    category: "Government Services",
    subcategory: "Office Access",
    location: { district: "Ranchi", block: "Ormanjhi", village: "Ormanjhi", lat: 23.49, lng: 85.51 },
    affectedPopulation: 260,
    urgency: "Medium",
    severity: "Medium",
    priorityScore: 63,
    innovationScore: 66,
    status: "SUBMITTED",
    reportCount: 1,
    createdAt: daysAgo(2),
  }),
  mk({
    id: "ch-1008",
    title: "Monsoon waterlogging in Mango and Dimna Road",
    description: "Low-lying areas flood within an hour of heavy rain. Drains are clogged with silt and plastic; shops lose stock every monsoon.",
    category: "Environment",
    subcategory: "Flooding & Waterlogging",
    location: { district: "East Singhbhum", block: "Jamshedpur", village: "Mango", lat: 22.83, lng: 86.21 },
    affectedPopulation: 8000,
    urgency: "High",
    priorityScore: 82,
    innovationScore: 72,
    status: "UNDER_REVIEW",
    reportCount: 16,
    createdAt: daysAgo(9),
  }),
  mk({
    id: "ch-1009",
    title: "No public bus between Chas and rural blocks after 6 pm",
    description: "Workers and students returning after 6 pm have no public transport. Private jeeps overcharge and are unsafe for women.",
    category: "Transport",
    subcategory: "Public Bus Service",
    location: { district: "Bokaro", block: "Chas", village: "Chas", lat: 23.63, lng: 86.17 },
    affectedPopulation: 3000,
    urgency: "Medium",
    severity: "Medium",
    priorityScore: 66,
    innovationScore: 70,
    status: "SUBMITTED",
    reportCount: 3,
    createdAt: daysAgo(5),
  }),
  mk({
    id: "ch-1010",
    title: "Irrigation canal silted; rabi crop dependent on rain",
    description: "The minor irrigation canal has not been de-silted in years. Farmers cannot grow a second crop and migrate seasonally for work.",
    category: "Agriculture",
    subcategory: "Irrigation",
    location: { district: "Giridih", block: "Bengabad", village: "Bengabad", lat: 24.24, lng: 86.4 },
    affectedPopulation: 1500,
    urgency: "Medium",
    priorityScore: 72,
    innovationScore: 68,
    status: "RESOLVED",
    reportCount: 6,
    createdAt: daysAgo(180),
    timeline: [
      { status: "SUBMITTED", at: daysAgo(180), by: "Citizen" },
      { status: "VALIDATED", at: daysAgo(170), by: "R. K. Sinha" },
      { status: "MATCHED", at: daysAgo(165), by: "R. K. Sinha" },
      { status: "PROJECT_CREATED", at: daysAgo(150), by: "BIT Mesra" },
      { status: "IN_PROGRESS", at: daysAgo(120), by: "BIT Mesra" },
      { status: "RESOLVED", at: daysAgo(20), by: "R. K. Sinha", note: "Canal desilting plan deployed with district authority" },
    ],
  }),
];

// Similar water reports clustered under the master challenge
const villages = ["Kondra", "Raidih", "Sursang", "Parsa", "Kolebira Tola", "Bhurso", "Silam", "Jargo"];
export const CLUSTER_REPORTS: Challenge[] = Array.from({ length: 22 }, (_, i) =>
  mk({
    id: `ch-c${i + 1}`,
    code: `JH-CH-C${String(i + 1).padStart(2, "0")}`,
    title: ["Yellow water from handpump", "Children falling sick after drinking well water", "Metallic taste in tap water", "Handpump water unfit for drinking"][i % 4]!,
    description: `Report from ${villages[i % villages.length]} village about discoloured drinking water.`,
    category: "Water & Sanitation",
    subcategory: "Drinking Water",
    location: { district: "Gumla", block: "Raidih", village: villages[i % villages.length]!, lat: 22.98 + (i % 5) * 0.008 - 0.016, lng: 84.36 + (i % 4) * 0.01 - 0.015 },

    affectedPopulation: 20 + i * 7,
    status: "MERGED",
    clusterId: "cl-1",
    createdAt: daysAgo(62 - i),
  }),
);

export const PROJECTS: Project[] = [
  {
    id: "prj-1",
    code: "JH-PRJ-001",
    title: "IoT-based Rural Water Quality Monitoring",
    challengeId: "ch-1001",
    universityId: "uni-iiitr",
    facultyMentorId: "fac-1",
    studentIds: ["stu-1", "stu-3", "stu-5", "stu-7"],
    requiredSkills: ["Embedded C", "Sensor calibration", "Water chemistry", "Community engagement"],
    industryPartnerIds: ["ind-jwt"],
    proposalId: "prop-1",
    status: "PROTOTYPE",
    requiredSupport: ["₹2L funding", "IoT hardware", "Technical mentor", "Pilot partner"],
    estimatedBudget: "₹4.5 Lakh",
    collaborations: [
      { id: "col-1", projectId: "prj-1", partnerId: "ind-jwt", partnerName: "Jharkhand Water Tech Pvt Ltd", contributionTypes: ["Hardware", "Technology"], estimatedSupport: "12 sensor nodes (₹1.2L)", message: "We can supply calibrated TDS/turbidity sensor kits.", status: "ACCEPTED", at: daysAgo(30) },
    ],
    impactMetrics: [],
    createdAt: daysAgo(49),
    milestones: [
      { id: "ms-1", name: "Research", deadline: daysAgo(30), owner: "Dr. Manoj Tirkey", status: "Completed", documents: ["baseline-water-survey.pdf"], comments: [{ author: "Dr. Manoj Tirkey", text: "Baseline samples from 14 handpumps collected and analysed.", at: daysAgo(31) }] },
      { id: "ms-2", name: "Prototype", deadline: new Date(Date.now() + 12 * 864e5).toISOString(), owner: "Rohit Kumar", status: "In Progress", documents: ["sensor-node-v1-schematic.pdf"], comments: [{ author: "Dr. Priya Kumari", text: "LoRa node prototype tested in lab; field enclosure pending.", at: daysAgo(4) }] },
      { id: "ms-3", name: "Testing", deadline: new Date(Date.now() + 40 * 864e5).toISOString(), owner: "Sandeep Lakra", status: "Pending", documents: [], comments: [] },
      { id: "ms-4", name: "Pilot", deadline: new Date(Date.now() + 75 * 864e5).toISOString(), owner: "Kunal Prasad", status: "Pending", documents: [], comments: [] },
      { id: "ms-5", name: "Deployment", deadline: new Date(Date.now() + 120 * 864e5).toISOString(), owner: "Dr. Priya Kumari", status: "Pending", documents: [], comments: [] },
    ],
  },
  {
    id: "prj-2",
    code: "JH-PRJ-002",
    title: "Solar Microgrid for Kolebira Hamlets",
    challengeId: "ch-1006",
    universityId: "uni-nit",
    
    studentIds: [],
    requiredSkills: ["Power electronics", "Battery systems"],
    industryPartnerIds: [],
    status: "PROPOSAL",
    requiredSupport: ["₹6L funding", "Solar panels & inverters", "Deployment partner"],
    estimatedBudget: "₹9 Lakh",
    collaborations: [],
    impactMetrics: [],
    createdAt: daysAgo(20),
    milestones: [
      { id: "ms-6", name: "Research", deadline: new Date(Date.now() + 10 * 864e5).toISOString(), owner: "NIT Jamshedpur", status: "In Progress", documents: [], comments: [] },
      { id: "ms-7", name: "Prototype", deadline: new Date(Date.now() + 50 * 864e5).toISOString(), owner: "NIT Jamshedpur", status: "Pending", documents: [], comments: [] },
      { id: "ms-8", name: "Testing", deadline: new Date(Date.now() + 80 * 864e5).toISOString(), owner: "NIT Jamshedpur", status: "Pending", documents: [], comments: [] },
      { id: "ms-9", name: "Pilot", deadline: new Date(Date.now() + 110 * 864e5).toISOString(), owner: "NIT Jamshedpur", status: "Pending", documents: [], comments: [] },
      { id: "ms-10", name: "Deployment", deadline: new Date(Date.now() + 150 * 864e5).toISOString(), owner: "NIT Jamshedpur", status: "Pending", documents: [], comments: [] },
    ],
  },
  {
    id: "prj-3",
    code: "JH-PRJ-003",
    title: "Bengabad Canal Desilting & Smart Scheduling",
    challengeId: "ch-1010",
    universityId: "uni-bit",
    studentIds: [],
    requiredSkills: [],
    industryPartnerIds: ["ind-ccl"],
    status: "IMPACT_MEASUREMENT",
    requiredSupport: [],
    estimatedBudget: "₹12 Lakh",
    collaborations: [],
    impactMetrics: [
      { id: "im-1", projectId: "prj-3", label: "Farmers with second crop", value: 1180, unit: "people", recordedAt: daysAgo(20) },
      { id: "im-2", projectId: "prj-3", label: "Hectares irrigated", value: 420, unit: "ha", recordedAt: daysAgo(20) },
    ],
    createdAt: daysAgo(150),
    milestones: ["Research", "Prototype", "Testing", "Pilot", "Deployment"].map((n, i) => ({
      id: `ms-p3-${i}`,
      name: n as Project["milestones"][number]["name"],
      deadline: daysAgo(140 - i * 25),
      owner: "BIT Mesra",
      status: "Completed" as const,
      documents: [],
      comments: [],
    })),
  },
];

export const NOTIFICATIONS: Notification[] = [
  { id: "n-1", role: "CITIZEN", title: "Your challenge has been validated", body: "Drinking water contamination in Raidih block was validated and merged with 22 similar reports.", at: daysAgo(57), read: true, link: "/challenges/ch-1001" },
  { id: "n-2", role: "CITIZEN", title: "Project started on your challenge", body: "IIIT Ranchi has begun prototyping an IoT water-quality monitoring solution.", at: daysAgo(40), read: false, link: "/challenges/ch-1001" },
  { id: "n-3", role: "ADMIN", title: "23 similar challenges detected", body: "AI-assisted analysis grouped 23 water reports in Raidih block, Gumla.", at: daysAgo(58), read: true, link: "/admin/challenges/ch-1001" },
  { id: "n-4", role: "ADMIN", title: "Pending validation", body: "4 challenges awaiting validation, including a critical healthcare access report from Palamu.", at: daysAgo(1), read: false, link: "/admin/challenges" },
  { id: "n-5", role: "UNIVERSITY", title: "New challenge matched your institution", body: "Paddy blast disease in Hazaribagh — 88% match with IIIT Ranchi.", at: daysAgo(18), read: false, link: "/university" },
  { id: "n-6", role: "UNIVERSITY", title: "Industry partner joined", body: "Jharkhand Water Tech will supply 12 sensor nodes for JH-PRJ-001.", at: daysAgo(30), read: true, link: "/university/projects/prj-1" },
  { id: "n-7", role: "INDUSTRY", title: "IIIT Ranchi is seeking industry support", body: "Rural Water Quality Monitoring needs ₹2L funding and a pilot partner.", at: daysAgo(35), read: false, link: "/industry/projects/prj-1" },
  { id: "n-8", role: "INDUSTRY", title: "NIT Jamshedpur seeking deployment partner", body: "Solar microgrid project for Kolebira hamlets, Simdega.", at: daysAgo(15), read: false, link: "/industry/projects/prj-2" },
];

export const DISTRICTS = [
  "Ranchi", "Dhanbad", "East Singhbhum", "Bokaro", "Hazaribagh", "Giridih", "Palamu", "Gumla", "Dumka", "Simdega",
  "Deoghar", "Garhwa", "Latehar", "Lohardaga", "Khunti", "Ramgarh", "Koderma", "Chatra", "Godda", "Sahibganj",
  "Pakur", "Jamtara", "Saraikela-Kharsawan", "West Singhbhum",
];

export const IMPACT_SNAPSHOT = [
  { label: "Challenges Reported", value: 1284 },
  { label: "Challenges Validated", value: 412 },
  { label: "Universities Connected", value: 18 },
  { label: "Industry Partners", value: 37 },
  { label: "Solutions Deployed", value: 26 },
  { label: "Citizens Impacted", value: 48200 },
];
